import type { RoteiroStep } from "./store";

export interface ModeloEncontro {
  id: string;
  tema: string;
  categoria: string;
  leituraBiblica: string;
  materialApoio: string;
  roteiro: Omit<RoteiroStep, "id">[];
}

function step(tipo: RoteiroStep["tipo"], label: string, conteudo: string, tempo: number, oracaoTipo?: RoteiroStep["oracaoTipo"]): Omit<RoteiroStep, "id"> {
  return { tipo, label, conteudo, tempo, catequista: "", oracaoTipo };
}

export const CATEGORIAS_MODELOS = [
  "Jesus Cristo",
  "Santíssima Trindade",
  "Maria",
  "Dogmas Marianos",
  "Tempo Litúrgico",
  "História da Igreja",
  "Bíblia",
  "Novíssimos",
  "Missão",
  "Parábolas",
  "Vida de Jesus",
  "Cartas de Paulo",
  "Antigo Testamento",
  "Sacramentos",
  "Moral e Ética",
  "Oração",
  "Catequese Infantil",
  "Adolescentes",
  "Juventude",
  "Catequese com as Famílias",
  "Tempo Comum",
  "Tempo da Quaresma",
  "Tempo Pascal",
  "Tempo do Advento",
  "Solenidades e Festas",
  "Vocações",
  "Mandamentos da Igreja",
  "Mês da Bíblia",
];

export const MODELOS_ENCONTROS: ModeloEncontro[] = [
  // Jesus Cristo
  {
    id: "m1", tema: "Quem é Jesus Cristo?", categoria: "Jesus Cristo",
    leituraBiblica: "Jo 14,6 - Eu sou o caminho, a verdade e a vida",
    materialApoio: "Catecismo da Igreja Católica §422-451",
    roteiro: [
      step("acolhida", "Acolhida", "Receber os catequizandos com música de acolhida. Perguntar: quem é Jesus para você?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração Simples pedindo a presença do Espírito Santo", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Apresentar Jesus como Deus verdadeiro e homem verdadeiro. Usar imagens e passagens bíblicas sobre seus milagres e ensinamentos.", 20),
      step("dinamica", "Dinâmica", "Cada catequizando escreve uma carta para Jesus expressando o que sente por Ele.", 15),
      step("compromisso", "Compromisso", "Ler um trecho do Evangelho todos os dias desta semana.", 5),
      step("avisos", "Avisos", "Informes gerais da comunidade.", 3),
      step("oracao_final", "Oração Final", "Pai Nosso e Ave Maria em conjunto.", 5),
    ],
  },
  {
    id: "m2", tema: "Jesus, o Bom Pastor", categoria: "Jesus Cristo",
    leituraBiblica: "Jo 10,11-18 - Eu sou o Bom Pastor",
    materialApoio: "Documento de Aparecida §243-245",
    roteiro: [
      step("acolhida", "Acolhida", "Acolher com carinho. Perguntar o que sabem sobre um pastor de ovelhas.", 8),
      step("oracao_inicial", "Oração Inicial", "Salmo 23 - O Senhor é meu pastor", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Explicar a parábola do Bom Pastor e como Jesus cuida de cada um de nós.", 20),
      step("dinamica", "Dinâmica", "Desenhar uma ovelha e escrever nela algo que precisam que Jesus cuide.", 15),
      step("compromisso", "Compromisso", "Ser 'bom pastor' para alguém esta semana: ajudar, cuidar, acolher.", 5),
      step("avisos", "Avisos", "Informes da catequese.", 3),
      step("oracao_final", "Oração Final", "Oração espontânea de agradecimento.", 5),
    ],
  },
  // Santíssima Trindade
  {
    id: "m3", tema: "O Mistério da Santíssima Trindade", categoria: "Santíssima Trindade",
    leituraBiblica: "Mt 28,19 - Batizai em nome do Pai, do Filho e do Espírito Santo",
    materialApoio: "CIC §232-267",
    roteiro: [
      step("acolhida", "Acolhida", "Iniciar fazendo o sinal da cruz pausadamente e refletir sobre cada pessoa da Trindade.", 8),
      step("oracao_inicial", "Oração Inicial", "Glória ao Pai e louvor à Trindade", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Explicar que Deus é um só em três pessoas: Pai (criador), Filho (redentor), Espírito Santo (santificador). Usar analogias.", 25),
      step("dinamica", "Dinâmica", "Trevo de 3 folhas: cada folha representa uma pessoa da Trindade. Montar com papel.", 15),
      step("compromisso", "Compromisso", "Fazer o sinal da cruz com devoção durante a semana.", 3),
      step("avisos", "Avisos", "Avisos gerais.", 2),
      step("oracao_final", "Oração Final", "Oração ao Espírito Santo.", 5),
    ],
  },
  {
    id: "m4", tema: "Deus Pai Criador", categoria: "Santíssima Trindade",
    leituraBiblica: "Gn 1,1-31 - No princípio Deus criou o céu e a terra",
    materialApoio: "CIC §279-324",
    roteiro: [
      step("acolhida", "Acolhida", "Levar elementos da natureza (folhas, flores, pedras). Observar a beleza da criação.", 10),
      step("oracao_inicial", "Oração Inicial", "Cântico das Criaturas de São Francisco", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Refletir sobre Deus como Pai amoroso que nos criou. A criação como ato de amor.", 20),
      step("dinamica", "Dinâmica", "Painel coletivo: colar imagens da natureza e escrever agradecimentos a Deus Pai.", 15),
      step("compromisso", "Compromisso", "Cuidar da criação: plantar algo ou evitar desperdício.", 5),
      step("avisos", "Avisos", "Informes.", 3),
      step("oracao_final", "Oração Final", "Pai Nosso rezado lentamente.", 5),
    ],
  },
  // Maria
  {
    id: "m5", tema: "Maria, Mãe de Deus e nossa Mãe", categoria: "Maria",
    leituraBiblica: "Lc 1,26-38 - A Anunciação do Anjo a Maria",
    materialApoio: "CIC §484-511; Lumen Gentium Cap. VIII",
    roteiro: [
      step("acolhida", "Acolhida", "Montar um pequeno altar mariano com imagem de Nossa Senhora e flores.", 10),
      step("oracao_inicial", "Oração Inicial", "Ave Maria cantada", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A história de Maria desde a Anunciação. Seu sim a Deus. Por que é Mãe de Deus e Mãe nossa (Jo 19,26-27).", 20),
      step("dinamica", "Dinâmica", "Escrever uma oração pessoal para Nossa Senhora.", 15),
      step("compromisso", "Compromisso", "Rezar uma Ave Maria todos os dias desta semana.", 3),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Salve Rainha.", 5),
    ],
  },
  // Dogmas Marianos
  {
    id: "m6", tema: "A Imaculada Conceição", categoria: "Dogmas Marianos",
    leituraBiblica: "Lc 1,28 - Ave, cheia de graça!",
    materialApoio: "CIC §490-493; Ineffabilis Deus (Pio IX)",
    roteiro: [
      step("acolhida", "Acolhida", "Mostrar imagem de Nossa Senhora da Medalha Milagrosa. Conversar sobre pureza.", 8),
      step("oracao_inicial", "Oração Inicial", "Ofício da Imaculada Conceição", 7, "Ofício Divino"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Explicar que Maria foi preservada do pecado original desde sua concepção. Significado de 'cheia de graça'.", 20),
      step("dinamica", "Dinâmica", "Confeccionar a Medalha Milagrosa em papel e escrever uma graça pedida.", 15),
      step("compromisso", "Compromisso", "Pedir a intercessão de Maria Imaculada por uma intenção especial.", 3),
      step("avisos", "Avisos", "Informes.", 2),
      step("oracao_final", "Oração Final", "Oração à Imaculada Conceição.", 5),
    ],
  },
  {
    id: "m7", tema: "A Assunção de Maria", categoria: "Dogmas Marianos",
    leituraBiblica: "Ap 12,1 - Uma mulher vestida de sol",
    materialApoio: "CIC §966; Munificentissimus Deus (Pio XII)",
    roteiro: [
      step("acolhida", "Acolhida", "Contemplar imagem da Assunção de Maria. Dialogar sobre o céu.", 8),
      step("oracao_inicial", "Oração Inicial", "Magnificat - Cântico de Maria", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Maria foi elevada ao céu em corpo e alma. Significado para nossa fé e esperança na ressurreição.", 20),
      step("dinamica", "Dinâmica", "Fazer um mural com as glórias de Maria nos mistérios do Rosário.", 15),
      step("compromisso", "Compromisso", "Rezar um mistério do Rosário em família.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Consagração a Nossa Senhora.", 5),
    ],
  },
  // Tempo Litúrgico
  {
    id: "m8", tema: "O Ano Litúrgico", categoria: "Tempo Litúrgico",
    leituraBiblica: "Ecl 3,1-8 - Há um tempo para tudo",
    materialApoio: "CIC §1163-1178",
    roteiro: [
      step("acolhida", "Acolhida", "Montar o calendário litúrgico com cores no quadro.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração do tempo litúrgico atual", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Apresentar os tempos litúrgicos: Advento, Natal, Quaresma, Páscoa, Tempo Comum. Cores e significados.", 25),
      step("dinamica", "Dinâmica", "Montar uma roda do ano litúrgico colorida com cartolina.", 15),
      step("compromisso", "Compromisso", "Observar as cores na igreja e identificar o tempo litúrgico atual.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de acordo com o tempo litúrgico vigente.", 5),
    ],
  },
  {
    id: "m9", tema: "A Quaresma e a Conversão", categoria: "Tempo Litúrgico",
    leituraBiblica: "Jl 2,12-13 - Convertei-vos a mim de todo o coração",
    materialApoio: "CIC §1430-1439",
    roteiro: [
      step("acolhida", "Acolhida", "Ambiente com tecido roxo. Perguntar o que significa mudar de vida.", 8),
      step("oracao_inicial", "Oração Inicial", "Salmo 51 - Piedade, Senhor", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Os três pilares da Quaresma: oração, jejum e esmola. O caminho de conversão.", 20),
      step("dinamica", "Dinâmica", "Cada um escreve em um papel algo que deseja mudar e coloca aos pés da cruz.", 15),
      step("compromisso", "Compromisso", "Praticar um ato de caridade e um pequeno jejum esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Via Sacra resumida.", 5),
    ],
  },
  // História da Igreja
  {
    id: "m10", tema: "O Nascimento da Igreja em Pentecostes", categoria: "História da Igreja",
    leituraBiblica: "At 2,1-13 - A vinda do Espírito Santo",
    materialApoio: "CIC §731-741",
    roteiro: [
      step("acolhida", "Acolhida", "Chamas de papel no ambiente. Perguntar se já sentiram o Espírito Santo.", 10),
      step("oracao_inicial", "Oração Inicial", "Vinde Espírito Santo - Veni Creator Spiritus", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Pentecostes como nascimento da Igreja. Os apóstolos recebem o Espírito e começam a evangelizar.", 20),
      step("dinamica", "Dinâmica", "Cada um recebe uma 'chama' de papel e escreve um dom do Espírito Santo que deseja.", 15),
      step("compromisso", "Compromisso", "Pedir ao Espírito Santo coragem para falar de Jesus.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração ao Espírito Santo.", 5),
    ],
  },
  {
    id: "m11", tema: "Os Primeiros Cristãos", categoria: "História da Igreja",
    leituraBiblica: "At 2,42-47 - A vida da primeira comunidade",
    materialApoio: "CIC §949-953",
    roteiro: [
      step("acolhida", "Acolhida", "Formar uma roda e partilhar um pão. Conversar sobre comunidade.", 10),
      step("oracao_inicial", "Oração Inicial", "Leitura orante de Atos 2,42-47", 7, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Como viviam os primeiros cristãos: oração, partilha, Eucaristia, perseguições e testemunho.", 20),
      step("dinamica", "Dinâmica", "Comparar a vida dos primeiros cristãos com a comunidade hoje. O que podemos melhorar?", 15),
      step("compromisso", "Compromisso", "Participar mais ativamente da vida da comunidade.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pelos cristãos perseguidos hoje.", 5),
    ],
  },
  // Bíblia
  {
    id: "m12", tema: "A Divisão da Bíblia", categoria: "Bíblia",
    leituraBiblica: "2Tm 3,16-17 - Toda Escritura é inspirada por Deus",
    materialApoio: "CIC §101-141; Dei Verbum",
    roteiro: [
      step("acolhida", "Acolhida", "Levar uma Bíblia e deixar todos manusearem. Perguntar se sabem quantos livros tem.", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo 119 - Lâmpada para meus pés", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "AT (46 livros) e NT (27 livros). Pentateuco, históricos, sapienciais, proféticos. Evangelhos, Atos, Cartas, Apocalipse.", 25),
      step("dinamica", "Dinâmica", "Jogo: sortear nomes de livros e os catequizandos classificam em AT ou NT.", 15),
      step("compromisso", "Compromisso", "Ler um capítulo da Bíblia por dia.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pela Palavra de Deus.", 5),
    ],
  },
  // Novíssimos
  {
    id: "m13", tema: "Céu, Purgatório e Inferno", categoria: "Novíssimos",
    leituraBiblica: "Jo 14,2-3 - Na casa do meu Pai há muitas moradas",
    materialApoio: "CIC §1020-1060",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: o que vocês acham que acontece depois da morte?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração pelas almas do purgatório", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O que a Igreja ensina: Céu (comunhão plena com Deus), Purgatório (purificação), Inferno (separação definitiva). Juízo particular e final.", 25),
      step("dinamica", "Dinâmica", "Debate: como nossas escolhas hoje determinam nosso destino eterno?", 15),
      step("compromisso", "Compromisso", "Rezar pelos fiéis defuntos e viver com esperança no céu.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Credo - profissão de fé na vida eterna.", 5),
    ],
  },
  // Missão
  {
    id: "m14", tema: "A Missão de Todo Batizado", categoria: "Missão",
    leituraBiblica: "Mt 28,18-20 - Ide e fazei discípulos",
    materialApoio: "CIC §849-856; Evangelii Gaudium",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: você já falou de Jesus para alguém?", 8),
      step("oracao_inicial", "Oração Inicial", "Oração dos Missionários", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Todo batizado é missionário. A missão não é só para padres e religiosos. Como ser missionário no dia a dia.", 20),
      step("dinamica", "Dinâmica", "Planejar uma ação missionária para a comunidade.", 15),
      step("compromisso", "Compromisso", "Convidar alguém para a missa ou catequese.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de envio missionário.", 5),
    ],
  },
  // Parábolas
  {
    id: "m15", tema: "A Parábola do Filho Pródigo", categoria: "Parábolas",
    leituraBiblica: "Lc 15,11-32 - O Pai misericordioso",
    materialApoio: "CIC §1439; Misericordiae Vultus",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: vocês já erraram e foram perdoados?", 8),
      step("oracao_inicial", "Oração Inicial", "Salmo 103 - O Senhor é misericordioso", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Leitura e análise da parábola. O amor do Pai, o arrependimento do filho, a inveja do irmão mais velho.", 20),
      step("dinamica", "Dinâmica", "Dramatização da parábola pelos catequizandos.", 20),
      step("compromisso", "Compromisso", "Pedir perdão a alguém e perdoar quem nos magoou.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Ato de contrição.", 5),
    ],
  },
  {
    id: "m16", tema: "A Parábola do Semeador", categoria: "Parábolas",
    leituraBiblica: "Mt 13,1-23 - O semeador saiu a semear",
    materialApoio: "CIC §546",
    roteiro: [
      step("acolhida", "Acolhida", "Levar sementes e diferentes tipos de solo (pedra, espinhos, terra boa).", 10),
      step("oracao_inicial", "Oração Inicial", "Louvor com música sobre a Palavra", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Os quatro tipos de solo representam nosso coração. Como acolhemos a Palavra de Deus?", 20),
      step("dinamica", "Dinâmica", "Plantar uma semente em um copo. Cuidar durante a semana como sinal de fé.", 15),
      step("compromisso", "Compromisso", "Ser 'terra boa': ouvir a Palavra e colocá-la em prática.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pela fecundidade da Palavra.", 5),
    ],
  },
  {
    id: "m17", tema: "A Parábola do Bom Samaritano", categoria: "Parábolas",
    leituraBiblica: "Lc 10,25-37 - Quem é o meu próximo?",
    materialApoio: "CIC §1932; Fratelli Tutti",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: quem é o nosso próximo hoje?", 8),
      step("oracao_inicial", "Oração Inicial", "Oração pela paz e fraternidade", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Análise da parábola: o sacerdote, o levita e o samaritano. Quem realmente amou?", 20),
      step("dinamica", "Dinâmica", "Listar situações do dia a dia onde podemos ser bons samaritanos.", 15),
      step("compromisso", "Compromisso", "Ajudar alguém necessitado esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de São Francisco - Senhor, fazei-me instrumento.", 5),
    ],
  },
  {
    id: "m18", tema: "A Parábola das Dez Virgens", categoria: "Parábolas",
    leituraBiblica: "Mt 25,1-13 - Vigiai, pois não sabeis o dia nem a hora",
    materialApoio: "CIC §672; 1036",
    roteiro: [
      step("acolhida", "Acolhida", "Acender velas no ambiente. Perguntar sobre estar preparado.", 8),
      step("oracao_inicial", "Oração Inicial", "Oração de vigilância", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A importância da vigilância e da preparação espiritual. As virgens prudentes e as insensatas.", 20),
      step("dinamica", "Dinâmica", "Cada um decora sua própria 'lâmpada' de papel com compromissos de fé.", 15),
      step("compromisso", "Compromisso", "Manter a 'lâmpada acesa': oração diária e boas obras.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Maranatha - Vem, Senhor Jesus!", 5),
    ],
  },
  // Vida de Jesus
  {
    id: "m19", tema: "A Anunciação e o Natal de Jesus", categoria: "Vida de Jesus",
    leituraBiblica: "Lc 2,1-20 - O nascimento de Jesus",
    materialApoio: "CIC §484-486; 525-526",
    roteiro: [
      step("acolhida", "Acolhida", "Montar um presépio simples. Conversar sobre o Natal verdadeiro.", 10),
      step("oracao_inicial", "Oração Inicial", "Noite Feliz ou canto natalino", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Da Anunciação ao Nascimento: o sim de Maria, a viagem a Belém, o nascimento na manjedoura, os pastores e os magos.", 25),
      step("dinamica", "Dinâmica", "Montar um presépio com materiais recicláveis.", 15),
      step("compromisso", "Compromisso", "Viver o espírito do Natal: simplicidade e partilha.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração diante do presépio.", 5),
    ],
  },
  {
    id: "m20", tema: "A Via Sacra de Jesus", categoria: "Vida de Jesus",
    leituraBiblica: "Lc 23,26-49 - A crucificação de Jesus",
    materialApoio: "CIC §595-623",
    roteiro: [
      step("acolhida", "Acolhida", "Ambiente com cruz e tecido roxo. Momento de silêncio.", 8),
      step("oracao_inicial", "Oração Inicial", "Canto penitencial", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "As 14 estações da Via Sacra: da condenação ao sepultamento. O significado de cada estação para nossa vida.", 25),
      step("dinamica", "Dinâmica", "Percorrer as estações pelo espaço com imagens e orações em cada parada.", 20),
      step("compromisso", "Compromisso", "Carregar com paciência as cruzes do dia a dia.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração diante do crucifixo.", 5),
    ],
  },
  // Cartas de Paulo
  {
    id: "m21", tema: "São Paulo e suas Cartas", categoria: "Cartas de Paulo",
    leituraBiblica: "1Cor 13,1-13 - O Hino ao Amor",
    materialApoio: "CIC §2705; Introdução às Cartas Paulinas",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: vocês já escreveram uma carta para alguém?", 8),
      step("oracao_inicial", "Oração Inicial", "Oração de São Paulo pela comunidade", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Quem foi São Paulo: de perseguidor a apóstolo. Suas viagens missionárias e cartas às comunidades.", 20),
      step("dinamica", "Dinâmica", "Escrever uma 'carta' à comunidade, inspirados em Paulo.", 15),
      step("compromisso", "Compromisso", "Ler um trecho de uma carta de Paulo cada dia.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Bênção paulina: A graça do Senhor Jesus esteja convosco.", 5),
    ],
  },
  // Antigo Testamento
  {
    id: "m22", tema: "A Criação do Mundo", categoria: "Antigo Testamento",
    leituraBiblica: "Gn 1,1 - 2,4 - A criação em sete dias",
    materialApoio: "CIC §279-324; Laudato Si'",
    roteiro: [
      step("acolhida", "Acolhida", "Levar fotos da natureza. Perguntar: de onde veio tudo isso?", 10),
      step("oracao_inicial", "Oração Inicial", "Cântico das Criaturas", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Os sete dias da criação como narrativa teológica. O ser humano como imagem e semelhança de Deus.", 20),
      step("dinamica", "Dinâmica", "Fazer um mural dos 7 dias da criação com desenhos e colagens.", 15),
      step("compromisso", "Compromisso", "Agradecer a Deus pela criação e cuidar do meio ambiente.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pela casa comum.", 5),
    ],
  },
  {
    id: "m23", tema: "Os Patriarcas: Abraão, Isaac e Jacó", categoria: "Antigo Testamento",
    leituraBiblica: "Gn 12,1-4 - A vocação de Abraão",
    materialApoio: "CIC §59-61; 145-147",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: vocês já tiveram que confiar em alguém sem saber o resultado?", 8),
      step("oracao_inicial", "Oração Inicial", "Oração de confiança em Deus", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A história dos patriarcas: a fé de Abraão, a promessa a Isaac, as 12 tribos de Jacó. A aliança de Deus.", 25),
      step("dinamica", "Dinâmica", "Árvore genealógica dos patriarcas montada em grupo.", 15),
      step("compromisso", "Compromisso", "Confiar em Deus mesmo quando o caminho é incerto.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de Abraão: Creio, Senhor!", 5),
    ],
  },
  {
    id: "m24", tema: "Moisés e a Libertação do Egito", categoria: "Antigo Testamento",
    leituraBiblica: "Ex 3,1-15 - A sarça ardente",
    materialApoio: "CIC §62-64; 2575-2577",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: de que situações difíceis vocês gostariam de ser libertados?", 10),
      step("oracao_inicial", "Oração Inicial", "Cântico de Moisés - Ex 15", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A história de Moisés: nascimento, sarça ardente, pragas, travessia do Mar Vermelho, os 10 mandamentos.", 25),
      step("dinamica", "Dinâmica", "Os 10 mandamentos escritos em 'tábuas' de cartolina para levar para casa.", 15),
      step("compromisso", "Compromisso", "Viver um dos mandamentos de forma concreta.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pelos que sofrem escravidão hoje.", 5),
    ],
  },
  // Sacramentos
  {
    id: "m25", tema: "Os Sete Sacramentos", categoria: "Sacramentos",
    leituraBiblica: "Mt 28,19-20 - Batizando-os em nome do Pai...",
    materialApoio: "CIC §1210-1666",
    roteiro: [
      step("acolhida", "Acolhida", "Levar símbolos: água, óleo, pão, vinho, anel, estola. Perguntar o que representam.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração pelos sacramentos recebidos", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Os 7 sacramentos: Batismo, Confirmação, Eucaristia, Penitência, Unção dos Enfermos, Ordem, Matrimônio.", 25),
      step("dinamica", "Dinâmica", "Jogo da memória com símbolos e nomes dos sacramentos.", 15),
      step("compromisso", "Compromisso", "Participar do sacramento da reconciliação esta semana.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de ação de graças pelos sacramentos.", 5),
    ],
  },
  // Moral e Ética
  {
    id: "m26", tema: "Os Dez Mandamentos", categoria: "Moral e Ética",
    leituraBiblica: "Ex 20,1-17 - Os mandamentos de Deus",
    materialApoio: "CIC §2052-2082",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: por que existem regras? O que aconteceria sem elas?", 8),
      step("oracao_inicial", "Oração Inicial", "Salmo 19 - A lei do Senhor é perfeita", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Os 10 mandamentos como caminho de amor a Deus e ao próximo. Jesus resume em dois mandamentos.", 20),
      step("dinamica", "Dinâmica", "Cada grupo recebe mandamentos e cria situações do cotidiano onde se aplicam.", 15),
      step("compromisso", "Compromisso", "Viver conscientemente um mandamento por dia.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de compromisso com a lei de Deus.", 5),
    ],
  },
  // Oração
  {
    id: "m27", tema: "O Pai Nosso - A Oração do Senhor", categoria: "Oração",
    leituraBiblica: "Mt 6,9-13 - Quando orardes, dizei: Pai nosso...",
    materialApoio: "CIC §2759-2865",
    roteiro: [
      step("acolhida", "Acolhida", "Rezar o Pai Nosso juntos e perguntar se entendem cada parte.", 8),
      step("oracao_inicial", "Oração Inicial", "Pai Nosso cantado", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Analisar cada pedido do Pai Nosso: significado e implicações para a vida cristã.", 25),
      step("dinamica", "Dinâmica", "Escrever o Pai Nosso com as próprias palavras.", 15),
      step("compromisso", "Compromisso", "Rezar o Pai Nosso com atenção todas as manhãs.", 3),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Pai Nosso meditado lentamente.", 5),
    ],
  },
  // More parables
  {
    id: "m28", tema: "A Parábola dos Talentos", categoria: "Parábolas",
    leituraBiblica: "Mt 25,14-30 - A parábola dos talentos",
    materialApoio: "CIC §1880; Christifideles Laici",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: quais são seus talentos e habilidades?", 8),
      step("oracao_inicial", "Oração Inicial", "Oração de oferta dos dons", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Deus dá talentos a cada um. Somos responsáveis por multiplicá-los para o bem do Reino.", 20),
      step("dinamica", "Dinâmica", "Cada um lista 3 talentos e como pode usá-los a serviço da comunidade.", 15),
      step("compromisso", "Compromisso", "Usar um talento para ajudar alguém esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de oferta pessoal.", 5),
    ],
  },
  {
    id: "m29", tema: "A Parábola do Joio e do Trigo", categoria: "Parábolas",
    leituraBiblica: "Mt 13,24-30.36-43 - O joio e o trigo",
    materialApoio: "CIC §681-682",
    roteiro: [
      step("acolhida", "Acolhida", "Mostrar imagens de trigo e joio. Perguntar se sabem a diferença.", 8),
      step("oracao_inicial", "Oração Inicial", "Oração de discernimento", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O bem e o mal coexistem. A paciência de Deus. O juízo final e a misericórdia divina.", 20),
      step("dinamica", "Dinâmica", "Separar em dois grupos: ações que são 'trigo' e ações que são 'joio' em nossa vida.", 15),
      step("compromisso", "Compromisso", "Cultivar o 'trigo': fazer o bem mesmo quando o mal está presente.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pela conversão dos pecadores.", 5),
    ],
  },
  {
    id: "m30", tema: "A Parábola da Ovelha Perdida", categoria: "Parábolas",
    leituraBiblica: "Lc 15,1-7 - Alegria pela ovelha reencontrada",
    materialApoio: "CIC §545; 1443",
    roteiro: [
      step("acolhida", "Acolhida", "Esconder uma ovelha de pelúcia ou papel. Pedir que encontrem.", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo 23 cantado", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O amor de Deus por cada pessoa. Ele deixa as 99 para buscar a que se perdeu.", 20),
      step("dinamica", "Dinâmica", "Cada um escreve o nome de alguém que está 'perdido' e reza por essa pessoa.", 15),
      step("compromisso", "Compromisso", "Acolher quem está afastado da comunidade.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pelos que estão longe de Deus.", 5),
    ],
  },
  // Catequese Infantil
  {
    id: "m31", tema: "Jesus é meu melhor amigo", categoria: "Catequese Infantil",
    leituraBiblica: "Jo 15,14 - Vós sois meus amigos",
    materialApoio: "Livro da Catequese Infantil; Figuras de Jesus com crianças",
    roteiro: [
      step("acolhida", "Acolhida", "Receber as crianças com música animada. Entregar um crachá de 'Amigo de Jesus'.", 10),
      step("oracao_inicial", "Oração Inicial", "Conversa espontânea com o Papai do Céu.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Contar a história de como Jesus amava as crianças. Explicar que Ele quer ser nosso amigo para sempre.", 15),
      step("dinamica", "Dinâmica", "O Cordão da Amizade: Passar um novelo de lã. Cada criança que segura a lã diz por que é amiga de Jesus e passa para outra, formando uma teia.", 15),
      step("compromisso", "Compromisso", "Falar de Jesus para um amiguinho da escola.", 5),
      step("avisos", "Avisos", "Informes para os pais no mural.", 3),
      step("oracao_final", "Oração Final", "Santo Anjo do Senhor.", 5),
    ],
  },
  {
    id: "m32", tema: "O Anjo da Guarda: meu companheiro", categoria: "Catequese Infantil",
    leituraBiblica: "Sl 91,11 - Ele dará ordens aos seus anjos",
    materialApoio: "Imagens de Anjos; Papel e lápis de cor",
    roteiro: [
      step("acolhida", "Acolhida", "Brincadeira do 'Siga o Mestre' para falar sobre quem nos guia.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração do Santo Anjo rezada em coro.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Explicar que Deus deu um anjo para cada um de nós para nos proteger e inspirar o bem.", 15),
      step("dinamica", "Dinâmica", "Desenhar seu anjo da guarda e colar algodão nas asas. No verso, escrever um segredo que contariam para o anjo.", 20),
      step("compromisso", "Compromisso", "Dar 'Boa Noite' ao anjo da guarda antes de dormir.", 3),
      step("avisos", "Avisos", "Informes.", 2),
      step("oracao_final", "Oração Final", "Oração espontânea pedindo proteção.", 5),
    ],
  },
  {
    id: "m33", tema: "A Criação é um Presente de Deus", categoria: "Catequese Infantil",
    leituraBiblica: "Gn 1,1 - No princípio Deus criou...",
    materialApoio: "Materiais da natureza (folhas, pedras); Tintas e pincéis",
    roteiro: [
      step("acolhida", "Acolhida", "Passeio rápido pelo pátio ou observação da janela para ver o céu e árvores.", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo 148 - Louvor de todas as criaturas (versão infantil).", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Apresentar os dias da criação como uma história de amor. O homem e a mulher como cuidadores do mundo.", 20),
      step("dinamica", "Dinâmica", "Pintura Coletiva: Um grande painel onde cada criança pinta uma parte da criação (sol, flores, animais) usando as mãos.", 20),
      step("compromisso", "Compromisso", "Cuidar de uma planta ou animal durante a semana.", 5),
      step("avisos", "Avisos", "Avisos gerais.", 2),
      step("oracao_final", "Oração Final", "Agradecimento por cada coisa criada.", 5),
    ],
  },
  // Adolescentes
  {
    id: "m34", tema: "Além das Aparências: Quem sou eu?", categoria: "Adolescentes",
    leituraBiblica: "1Sm 16,7 - Deus olha o coração",
    materialApoio: "Um espelho; Cartões coloridos; Música reflexiva",
    roteiro: [
      step("acolhida", "Acolhida", "Música ambiente. Perguntar: 'Se o mundo fosse cego, como você se descreveria?'.", 10),
      step("oracao_inicial", "Oração Inicial", "Silêncio interior e escuta do coração.", 5, "Contemplativa"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Refletir sobre a pressão estética e social. A visão de Deus sobre nós (imagem e semelhança).", 20),
      step("dinamica", "Dinâmica", "O Espelho do Coração: Cada adolescente olha no espelho e depois escreve no cartão 3 qualidades internas que Deus vê nele, mas que o mundo às vezes ignora.", 15),
      step("compromisso", "Compromisso", "Fazer um elogio sincero a alguém que costuma ser ignorado.", 5),
      step("avisos", "Avisos", "Avisos da turma.", 2),
      step("oracao_final", "Oração Final", "Oração pela autoaceitação.", 5),
    ],
  },
  {
    id: "m35", tema: "Influencers da Fé no Mundo Digital", categoria: "Adolescentes",
    leituraBiblica: "Mt 5,14 - Vós sois a luz do mundo",
    materialApoio: "Smartphone (opcional); Papel kraft; Canetas",
    roteiro: [
      step("acolhida", "Acolhida", "Debate rápido: Quem vocês seguem? Por quê?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração pedindo discernimento no uso das redes sociais.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Como ser luz em ambientes tóxicos. O testemunho cristão na internet e nos grupos de amigos.", 20),
      step("dinamica", "Dinâmica", "Rede Social Real: Em um grande papel, criar um perfil 'cristão' ideal: O que esse perfil postaria? Quem ele ajudaria? Como ele reagiria a haters?", 15),
      step("compromisso", "Compromisso", "Postar ou enviar uma mensagem de esperança para alguém esta semana.", 5),
      step("avisos", "Avisos", "Informes.", 2),
      step("oracao_final", "Oração Final", "Pai Nosso em unidade.", 5),
    ],
  },
  {
    id: "m36", tema: "Escolhas e Consequências", categoria: "Adolescentes",
    leituraBiblica: "Dt 30,19 - Escolhe, pois, a vida",
    materialApoio: "Dois caminhos marcados no chão; Dilemas escritos em papel",
    roteiro: [
      step("acolhida", "Acolhida", "Jogo do 'O que você prefere?' (escolhas bobas para aquecer).", 10),
      step("oracao_inicial", "Oração Inicial", "Oração ao Espírito Santo para pedir sabedoria.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A liberdade como dom e responsabilidade. Pequenas escolhas que definem grandes destinos.", 20),
      step("dinamica", "Dinâmica", "A Ponte das Escolhas: O grupo deve atravessar um caminho cheio de 'dilemas'. Para cada passo, devem decidir entre o caminho fácil (egoísmo) e o caminho de Jesus (sacrifício).", 20),
      step("compromisso", "Compromisso", "Parar e rezar antes de tomar uma decisão importante esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de compromisso com a verdade.", 5),
    ],
  },
  // Juventude
  {
    id: "m37", tema: "Cristo Vive e te quer vivo!", categoria: "Juventude",
    leituraBiblica: "Exortação Christus Vivit #1",
    materialApoio: "Vela grande; Velas pequenas para todos",
    roteiro: [
      step("acolhida", "Acolhida", "Abraço da paz e boas-vindas. Música de impacto.", 8),
      step("oracao_inicial", "Oração Inicial", "Leitura orante dos primeiros parágrafos de Christus Vivit.", 7, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O querigma para o jovem: O amor de Deus, a salvação em Jesus e a vida nova no Espírito.", 20),
      step("dinamica", "Dinâmica", "Incendiando a Comunidade: Com a luz da vela principal (Jesus), cada jovem acende a sua e diz um sonho que tem para a Igreja, formando um círculo de luz.", 15),
      step("compromisso", "Compromisso", "Viver a alegria cristã em um ambiente de estudo ou trabalho.", 5),
      step("avisos", "Avisos", "Avisos gerais.", 2),
      step("oracao_final", "Oração Final", "Consagração da juventude.", 5),
    ],
  },
  {
    id: "m38", tema: "Vocação: Onde está o meu lugar?", categoria: "Juventude",
    leituraBiblica: "Jr 1,5 - Antes de te formar, eu te conheci",
    materialApoio: "Mapas; Bússola visual; Papel e caneta",
    roteiro: [
      step("acolhida", "Acolhida", "Partilha: O que você quer ser quando 'crescer' e quem Deus quer que você seja?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração de Samuel: 'Fala, Senhor, que teu servo escuta'.", 5, "Contemplativa"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Diferença entre profissão e vocação. Vocação humana, cristã e específica (matrimônio, sacerdócio, vida consagrada).", 25),
      step("dinamica", "Dinâmica", "O Mapa do Propósito: Desenhar um mapa da própria vida até aqui e identificar onde Deus 'deixou marcas'. Onde a bússola aponta agora?", 20),
      step("compromisso", "Compromisso", "Conversar com alguém que vive sua vocação com alegria.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração pelas vocações.", 5),
    ],
  },
  {
    id: "m39", tema: "Protagonismo e Missão Jovem", categoria: "Juventude",
    leituraBiblica: "1Tm 4,12 - Ninguém despreze a tua juventude",
    materialApoio: "Peças de quebra-cabeça ou engrenagens de papel",
    roteiro: [
      step("acolhida", "Acolhida", "Vídeo motivacional sobre jovens que mudaram o mundo (ex: Carlo Acutis).", 10),
      step("oracao_inicial", "Oração Inicial", "Oração do Jovem Apóstolo.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O jovem não é o futuro, é o AGORA da Igreja (Papa Francisco). Como atuar nas pastorais e nos ambientes sociais.", 20),
      step("dinamica", "Dinâmica", "A Engrenagem da Missão: Cada jovem escreve em uma engrenagem um dom que possui. Ao montar o painel, percebem que se um parar, a missão da Igreja fica incompleta.", 15),
      step("compromisso", "Compromisso", "Assumir ou ajudar em uma tarefa prática na paróquia esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 2),
      step("oracao_final", "Oração Final", "Oração de envio missionário.", 5),
    ],
  },
  // NOVOS MODELOS BASEADOS NAS IMAGENS
  {
    id: "m40", tema: "2ª catequese - O amor de Deus e o pecado", categoria: "Catequese com as Famílias",
    leituraBiblica: "Lc 15,11-32 - O filho pródigo",
    materialApoio: "Quadro de Jesus misericordioso e uma vasilha com água benta.",
    roteiro: [
      step("acolhida", "Acolhida", "A(o) catequista, às portas do local preparado, dá as boas-vindas aos pais e catequizandos com alegria. Canto de acolhimento: 'Este pranto' (Eugenio Jorge).", 10),
      step("oracao_inicial", "Saudação e Oração", "Saudação: 'Em nome do Pai... Que o Deus da esperança os encha de toda alegria'. Oração espontânea ressaltando o quanto Deus nos ama e quão grande é a sua misericórdia.", 10, "Oração Simples"),
      step("desenvolvimento", "Leitura da Palavra", "Canto de aclamação. Proclamação do Evangelho de Lucas 15,11-32. Objetivo: Reconhecer Deus como fonte do amor e tomar consciência da misericórdia do Pai que perdoa.", 25),
      step("dinamica", "Dinâmica / Reflexão", "Partilha em família sobre o perdão e o amor incondicional de Deus.", 10),
      step("oracao_final", "Oração Final", "Canto meditativo: 'Onde reina o amor' (Taizé).", 5),
    ],
  },
  {
    id: "m41", tema: "1ª catequese - Jesus caminha conosco", categoria: "Catequese com as Famílias",
    leituraBiblica: "Lc 24,13-35 - Os discípulos de Emaús",
    materialApoio: "Bíblia, vela, imagem de Jesus.",
    roteiro: [
      step("acolhida", "Acolhida", "Recepção das famílias com música suave. Ambiente preparado para o diálogo.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração de abertura pedindo a companhia de Jesus.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Refletir sobre como Jesus nos acompanha nas dificuldades, assim como fez com os discípulos a caminho de Emaús.", 20),
      step("dinamica", "Dinâmica", "Cada família partilha um momento em que sentiram Jesus caminhar com eles.", 20),
      step("oracao_final", "Oração Final", "Preces espontâneas e Pai Nosso.", 5),
    ],
  },
  {
    id: "m42", tema: "Deus nos criou à sua imagem e semelhança", categoria: "Tempo Comum",
    leituraBiblica: "Gn 1,26-27 - Façamos o homem à nossa imagem",
    materialApoio: "Espelho, cartolina, lápis.",
    roteiro: [
      step("acolhida", "Acolhida", "Brincadeira do espelho (imitar o colega).", 10),
      step("oracao_inicial", "Oração Inicial", "Canto de louvor pela criação.", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento", "Explicar que somos a obra-prima de Deus, criados por amor para amar.", 25),
      step("dinamica", "Dinâmica", "Olhar-se no espelho e agradecer a Deus por uma qualidade própria.", 15),
      step("oracao_final", "Oração Final", "Oração de gratidão pela vida.", 5),
    ],
  },
  {
    id: "m43", tema: "Moisés recebe de Deus os Mandamentos", categoria: "Tempo Comum",
    leituraBiblica: "Ex 20,1-17 - Os Dez Mandamentos",
    materialApoio: "Duas tábuas de isopor ou papelão.",
    roteiro: [
      step("acolhida", "Acolhida", "Recepção com dinâmica sobre regras de convivência.", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo responsorial sobre a Lei do Senhor.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento", "A história de Moisés no Monte Sinai. As tábuas da Lei como um caminho de amor.", 25),
      step("dinamica", "Dinâmica", "Montar os 10 mandamentos nas tábuas da turma.", 15),
      step("oracao_final", "Oração Final", "Oração pedindo força para seguir os mandamentos.", 5),
    ],
  },
  {
    id: "m44", tema: "Advento: tempo de preparação", categoria: "Tempo do Advento",
    leituraBiblica: "Is 40,3-5 - Preparai o caminho do Senhor",
    materialApoio: "Coroa do Advento, velas coloridas.",
    roteiro: [
      step("acolhida", "Acolhida", "Apresentar a Coroa do Advento apagada.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração da primeira semana do Advento.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento", "Significado do Advento: vigilância, esperança, alegria e conversão. Esperar a vinda do Salvador.", 25),
      step("dinamica", "Dinâmica", "Escrever compromissos de mudança para preparar o coração como manjedoura.", 15),
      step("oracao_final", "Oração Final", "Canto 'Vem, Senhor Jesus'.", 5),
    ],
  },
  {
    id: "m45", tema: "A origem do pecado", categoria: "Tempo da Quaresma",
    leituraBiblica: "Gn 3,1-15 - A queda do homem",
    materialApoio: "Cruz de madeira, tecido roxo.",
    roteiro: [
      step("acolhida", "Acolhida", "Ambiente reflexivo, luz reduzida. Falar sobre escolhas ruins.", 10),
      step("oracao_inicial", "Oração Inicial", "Ato penitencial.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento", "A história de Adão e Eva. O que é o pecado e como ele nos afasta de Deus. A promessa de salvação.", 25),
      step("dinamica", "Dinâmica", "Escrever atitudes pecaminosas em papéis e colar numa cruz.", 15),
      step("oracao_final", "Oração Final", "Oração pedindo perdão.", 5),
    ],
  },
  {
    id: "m46", tema: "Domingo, dia do Senhor", categoria: "Tempo Pascal",
    leituraBiblica: "Jo 20,1-9 - A ressurreição no primeiro dia da semana",
    materialApoio: "Vela (Círio Pascal em miniatura), flores.",
    roteiro: [
      step("acolhida", "Acolhida", "Ambiente festivo e iluminado. Saudação de 'Feliz Páscoa'.", 10),
      step("oracao_inicial", "Oração Inicial", "Canto 'Aleluia'.", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento", "A ressurreição de Jesus no domingo. Por que guardamos o domingo. A importância da missa dominical.", 25),
      step("dinamica", "Dinâmica", "Desenhar como é (ou deveria ser) o domingo na família.", 15),
      step("oracao_final", "Oração Final", "Oração de júbilo pela vida nova em Cristo.", 5),
    ],
  },
  {
    id: "m47", tema: "Jesus Cristo, Rei do Universo", categoria: "Solenidades e Festas",
    leituraBiblica: "Jo 18,33-37 - Meu Reino não é deste mundo",
    materialApoio: "Coroa de espinhos e coroa dourada.",
    roteiro: [
      step("acolhida", "Acolhida", "Debate: O que faz um rei? Jesus foi um rei como os outros?", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo 93 - O Senhor é Rei.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento", "O reinado de Jesus é feito de amor, serviço e verdade, culminando na Cruz.", 25),
      step("dinamica", "Dinâmica", "Escolher ações que demonstram o Reino de Deus no mundo hoje.", 15),
      step("oracao_final", "Oração Final", "Oração a Cristo Rei.", 5),
    ],
  },

  // ── VOCAÇÕES ──────────────────────────────────────────────────────────────
  {
    id: "m48", tema: "A Vocação Sacerdotal", categoria: "Vocações",
    leituraBiblica: "Hb 5,1-6 - Todo Sumo Sacerdote é tomado dentre os homens",
    materialApoio: "CIC §1539-1553; Presbyterorum Ordinis; Fotos de ordenações sacerdotais",
    roteiro: [
      step("acolhida", "Acolhida", "Preparar o ambiente com uma estola e cálice sobre a mesa. Perguntar: vocês já pensaram no que é ser padre?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração pelas vocações sacerdotais — 'Senhor da Messe, mandai operários para a vossa messe'.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O que é a vocação sacerdotal: chamado de Deus, não escolha humana (Jo 15,16). O sacerdote age 'in persona Christi': celebra os sacramentos, anuncia o Evangelho e apascenta o povo. Falar sobre o sacerdócio ministerial e o sacerdócio comum dos fiéis. Testemunho: como reconhecer o chamado? Silêncio, oração, orientação espiritual.", 25),
      step("dinamica", "Dinâmica", "Roda de perguntas: 'O que admiro em um padre que conheço?' Cada catequizando partilha uma qualidade que percebe em um sacerdote de sua vida. Reflexão: qualquer dessas qualidades pode ser sinal de uma vocação?", 15),
      step("compromisso", "Compromisso", "Rezar esta semana pelo padre da paróquia e por jovens que possam estar sendo chamados.", 5),
      step("avisos", "Avisos", "Avisos da catequese.", 3),
      step("oracao_final", "Oração Final", "Ladainha dos Santos pedindo vocações sacerdotais.", 5),
    ],
  },
  {
    id: "m49", tema: "A Vocação Matrimonial", categoria: "Vocações",
    leituraBiblica: "Gn 2,18-24 - Não é bom que o homem esteja só",
    materialApoio: "CIC §1601-1666; Amoris Laetitia; Aliança matrimonial (símbolo de anel)",
    roteiro: [
      step("acolhida", "Acolhida", "Colocar dois anéis sobre a mesa. Perguntar: o que o casamento representa para vocês? O que faz um casamento dar certo?", 8),
      step("oracao_inicial", "Oração Inicial", "Leitura orante de Cântico dos Cânticos 2,10-13 — 'Levanta-te, amada minha'.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O matrimônio como Sacramento: não é apenas um contrato civil, mas uma aliança sagrada selada por Deus. As três notas essenciais: unidade (um só corpo), indissolubilidade (para sempre) e abertura à vida (filhos). O amor conjugal como imagem do amor de Cristo pela Igreja (Ef 5,25). Diferença entre amor-sentimento e amor-decisão. O que a Igreja ensina sobre namoro, noivado e preparação para o casamento.", 25),
      step("dinamica", "Dinâmica", "'As Quatro Linguagens do Amor' adaptada: apresentar as formas de amor (palavras, tempo de qualidade, serviço, toque físico respeitoso, presentes). Em grupos, criar situações de como um casal pode viver cada uma dessas linguagens de forma cristã.", 15),
      step("compromisso", "Compromisso", "Observar e agradecer a Deus por um casal que é exemplo de amor fiel na família ou comunidade.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração pelos casais da comunidade e pelos noivos que se preparam para o matrimônio.", 5),
    ],
  },
  {
    id: "m50", tema: "A Vocação para a Vida Religiosa", categoria: "Vocações",
    leituraBiblica: "Mt 19,27-29 - Deixamos tudo e te seguimos",
    materialApoio: "CIC §914-945; Perfectae Caritatis; Fotos de congregações religiosas",
    roteiro: [
      step("acolhida", "Acolhida", "Mostrar fotos de religiosos e religiosas de diferentes congregações. Perguntar: o que vocês sabem sobre a vida de quem se consagra a Deus?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração das Vésperas ou trecho do Ofício Divino rezado por religiosos.", 7, "Ofício Divino"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O que é a Vida Consagrada: religiosos e religiosas que respondem a um chamado especial de Deus para viver os três conselhos evangélicos — Pobreza (desapego dos bens), Castidade (entrega total a Deus) e Obediência (submissão à vontade de Deus). Diferentes formas: vida contemplativa (mosteiros), vida ativa (missão, saúde, educação), vida eremítica. Exemplos de santos: Santa Teresa de Ávila, São Bento, Madre Teresa de Calcutá, São Francisco de Assis. A vida religiosa como sinal do Reino de Deus.", 25),
      step("dinamica", "Dinâmica", "Entrevista imaginária: Em duplas, um faz o papel de um religioso/religiosa e o outro entrevista perguntando: Por que escolheu esse caminho? O que abre mão? O que ganha? Partilhar as respostas com o grupo.", 15),
      step("compromisso", "Compromisso", "Conhecer uma congregação religiosa presente na paróquia ou cidade e rezar pela sua missão.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração pelas religiosas e religiosos que dedicaram a vida a Deus.", 5),
    ],
  },
  {
    id: "m51", tema: "A Vocação Leiga", categoria: "Vocações",
    leituraBiblica: "1Cor 12,4-11 - Há diversidade de dons, mas o mesmo Espírito",
    materialApoio: "CIC §897-913; Christifideles Laici; Apostolicam Actuositatem",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: vocês sabem que podem ser santos sem ser padres ou freiras? Como? Deixar a pergunta no ar.", 8),
      step("oracao_inicial", "Oração Inicial", "Louvor e ação de graças pelos dons recebidos no Batismo.", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O que é a vocação leiga: o cristão batizado que vive sua fé no mundo secular — família, trabalho, escola, política, cultura. O leigo não é um 'cristão de segunda categoria': é chamado a santificar o mundo de dentro. Três ambientes de missão do leigo: a família (primeira escola de fé), o trabalho (oferecer a Deus o esforço diário) e a sociedade (ser fermento, sal e luz). Exemplos de leigos santos: São José, Carlos Acutis, Santa Gianna Beretta, Pier Giorgio Frassati. Participação em movimentos, pastorais e grupos de apostolado.", 25),
      step("dinamica", "Dinâmica", "'Onde estou no mundo?': Cada catequizando desenha uma figura humana no centro de uma folha. Ao redor, escreve os ambientes onde vive (escola, casa, time, trabalho, bairro). Em cada ambiente, identifica uma forma de ser 'luz do mundo' ali. Partilhar em duplas.", 15),
      step("compromisso", "Compromisso", "Identificar um ambiente da sua vida onde pode agir como cristão leigo missionário e praticar um gesto concreto esta semana.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração do leigo comprometido com o Reino.", 5),
    ],
  },

  // ── MANDAMENTOS DA IGREJA ─────────────────────────────────────────────────
  {
    id: "m52", tema: "Os Mandamentos da Igreja: Por que obedecer?", categoria: "Mandamentos da Igreja",
    leituraBiblica: "Mt 18,17-18 - Tudo o que ligardes na terra ficará ligado no Céu",
    materialApoio: "CIC §2041-2043; Lista dos 5 mandamentos da Igreja",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: vocês conhecem os mandamentos da Igreja? São diferentes dos 10 mandamentos de Deus? Anotar as respostas no quadro.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração ao Espírito Santo para iluminar o entendimento.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "A Igreja, guiada pelo Espírito Santo, tem autoridade para estabelecer normas que nos ajudem a viver a fé. Os mandamentos da Igreja não contradizem os de Deus — os complementam e aplicam à vida concreta. Apresentar a lista dos 5 mandamentos: 1) Participar da Missa aos domingos e festas de guarda; 2) Confessar os pecados graves ao menos uma vez por ano; 3) Receber a Sagrada Comunhão ao menos na Páscoa; 4) Abster-se de carne e jejuar nas sextas de Quaresma e Quarta-feira de Cinzas; 5) Suprir as necessidades materiais da Igreja.", 25),
      step("dinamica", "Dinâmica", "Quiz dos mandamentos: O catequista lê situações do dia a dia e os catequizandos identificam qual mandamento da Igreja se aplica a cada situação.", 15),
      step("compromisso", "Compromisso", "Memorizar os cinco mandamentos da Igreja e explicá-los para um familiar.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração de fidelidade à Igreja.", 5),
    ],
  },
  {
    id: "m53", tema: "1º Mandamento da Igreja: A Missa do Domingo", categoria: "Mandamentos da Igreja",
    leituraBiblica: "Jo 6,51-58 - Quem come a minha carne e bebe o meu sangue tem a vida eterna",
    materialApoio: "CIC §2042; 1389; Sacrosanctum Concilium",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: por que a maioria de nós vai à missa? Por obrigação ou por amor? Deixar responderem com honestidade.", 10),
      step("oracao_inicial", "Oração Inicial", "Canto de louvor eucarístico.", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O primeiro mandamento da Igreja pede que participemos da Missa aos domingos e festas de guarda (Natal, Assunção, etc.). Por quê? Porque a Eucaristia é o 'centro e cume' de toda a vida cristã (LG 11). Na Missa: ouvimos a Palavra de Deus, oferecemos nossa vida com a de Cristo, recebemos o Corpo e Sangue do Senhor e somos enviados em missão. Ausentar-se sem motivo grave é pecado grave. O domingo é o Dia do Senhor desde a Ressurreição.", 25),
      step("dinamica", "Dinâmica", "As Partes da Missa: Distribuir cartões com as partes da Missa (Ritos Iniciais, Liturgia da Palavra, Liturgia Eucarística, Rito de Comunhão, Rito de Envio). Em grupos, explicar o que acontece em cada parte e por que é importante.", 15),
      step("compromisso", "Compromisso", "Participar da próxima Missa com atenção e devoção, acompanhando cada parte conscientemente.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração de adoração eucarística.", 5),
    ],
  },
  {
    id: "m54", tema: "2º Mandamento da Igreja: A Confissão Anual", categoria: "Mandamentos da Igreja",
    leituraBiblica: "Jo 20,22-23 - Recebei o Espírito Santo. A quem perdoardes os pecados, serão perdoados",
    materialApoio: "CIC §1493; 2042; Rito da Penitência",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: faz quanto tempo que vocês não vão à confissão? Como se sentem antes e depois? Acolher as respostas com empatia e sem julgamento.", 10),
      step("oracao_inicial", "Oração Inicial", "Salmo 51 — 'Tem piedade de mim, ó Deus, na tua bondade'.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O segundo mandamento determina que todo cristão confesse seus pecados graves ao menos uma vez por ano. A Confissão (Sacramento da Penitência ou Reconciliação) não é uma punição — é um abraço de Deus. Cinco partes do Sacramento: Exame de Consciência, Contrição (dor dos pecados), Propósito de Emenda, Confissão oral dos pecados ao padre, Satisfação (penitência). O padre age em nome de Cristo: 'Ego te absolvo'. Depois da confissão: paz, alegria e força para começar de novo.", 25),
      step("dinamica", "Dinâmica", "O Exame de Consciência: Entregar uma folha com perguntas simples baseadas nos 10 mandamentos e nas virtudes. Catequizandos fazem o exame em silêncio. Ao final, todos rasgam o papel juntos como símbolo do perdão de Deus.", 15),
      step("compromisso", "Compromisso", "Fazer um exame de consciência antes de dormir esta semana e se preparar para uma confissão.", 5),
      step("avisos", "Avisos", "Avisos. Verificar próximas datas de confissão na paróquia.", 3),
      step("oracao_final", "Oração Final", "Ato de Contrição.", 5),
    ],
  },
  {
    id: "m55", tema: "3º Mandamento da Igreja: A Comunhão Pascal", categoria: "Mandamentos da Igreja",
    leituraBiblica: "1Cor 11,23-26 - Fazei isso em memória de mim",
    materialApoio: "CIC §1389; 2042; Semana Santa na catequese",
    roteiro: [
      step("acolhida", "Acolhida", "Perguntar: o que é a Páscoa para vocês? Além dos ovos de chocolate, o que a Igreja celebra? Conversar sobre a Ressurreição.", 8),
      step("oracao_inicial", "Oração Inicial", "Canto pascal de louvor — 'Aleluia, ele vive!'.", 5, "Louvor"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O terceiro mandamento exige que todo fiel receba a Sagrada Eucaristia ao menos uma vez por ano, no tempo pascal (entre Quarta-feira de Cinzas e a Santíssima Trindade). Por que ao menos na Páscoa? Porque é o memorial da morte e ressurreição de Jesus — o coração da fé cristã. Quem pode comungar: o batizado que não está em pecado grave. A importância de estar em graça para receber o Corpo de Cristo. A 'Comunhão espiritual' para quem não pode se aproximar.", 25),
      step("dinamica", "Dinâmica", "Linha do Tempo Pascal: Em grupo, montar uma linha do tempo da Semana Santa (Domingo de Ramos → Quinta da Ceia → Sexta da Paixão → Sábado Santo → Domingo de Páscoa), explicando o que acontece em cada dia e como isso se conecta à Eucaristia.", 15),
      step("compromisso", "Compromisso", "Participar das celebrações da Semana Santa na paróquia e receber a comunhão com devoção.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração de agradecimento pela Eucaristia.", 5),
    ],
  },
  {
    id: "m56", tema: "4º Mandamento da Igreja: Jejum e Abstinência", categoria: "Mandamentos da Igreja",
    leituraBiblica: "Mt 6,16-18 - Quando jejuardes, não tenhais cara de tristeza",
    materialApoio: "CIC §1438; 2043; Cânone 1249-1253",
    roteiro: [
      step("acolhida", "Acolhida", "Trazer para o encontro uma tigela vazia. Perguntar: o que significa passar sem comer voluntariamente? Por que alguém faria isso?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração de oferta do jejum.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O quarto mandamento pede abstinência de carne e jejum nas sextas-feiras da Quaresma e na Quarta-feira de Cinzas. Jejum: fazer apenas uma refeição completa no dia (maiores de 18 e menores de 60 anos). Abstinência: abster-se de carne (maiores de 14 anos). Por que fazemos isso? Para unir nosso sofrimento ao de Cristo na Cruz, fortalecer a vontade contra o pecado, solidarizar com os que passam fome. O jejum não é dieta — é oração do corpo. A tríade quaresmal: oração + jejum + esmola (Mt 6,1-18). Formas modernas de jejum: jejum de redes sociais, de entretenimento, de palavras negativas.", 25),
      step("dinamica", "Dinâmica", "'Meu jejum quaresmal': Cada catequizando escreve em um papel uma coisa de que vai abrir mão durante a Quaresma (ou durante a semana) e o motivo espiritual. Compartilhar em duplas e guardar como lembrete.", 15),
      step("compromisso", "Compromisso", "Praticar uma forma de jejum esta semana, unindo a privação a uma oração por uma intenção específica.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração pelos que passam fome no mundo.", 5),
    ],
  },
  {
    id: "m57", tema: "5º Mandamento da Igreja: Sustentar a Igreja", categoria: "Mandamentos da Igreja",
    leituraBiblica: "2Cor 9,6-8 - Deus ama quem dá com alegria",
    materialApoio: "CIC §2043; Cânone 222; Gaudium et Spes §76",
    roteiro: [
      step("acolhida", "Acolhida", "Trazer uma caixinha de doações ou dízimo. Perguntar: de onde vem o dinheiro para manter a paróquia, a catequese, as obras sociais?", 10),
      step("oracao_inicial", "Oração Inicial", "Canto de ofertório.", 5, "Celebrativo"),
      step("desenvolvimento", "Desenvolvimento do Tema", "O quinto mandamento nos convida a suprir as necessidades materiais da Igreja. Isso inclui: o dízimo (oferecer uma parte da renda), participar de coletas e campanhas, contribuir com trabalho voluntário e talentos. Por que a Igreja precisa de recursos? Para celebrar os sacramentos, manter os templos, sustentar os sacerdotes e religiosos, financiar obras sociais (hospitais, escolas, missões). Dar à Igreja não é 'pagar pelo religioso' — é participar da missão de Cristo no mundo. A Igreja não cobra pelo sacramento, mas depende da generosidade de seus membros.", 25),
      step("dinamica", "Dinâmica", "'O que a Igreja faz com o dinheiro?': Em grupos, listar as obras e serviços que a paróquia ou diocese realiza. Calcular (de forma simbólica) quantas pessoas ajudaria se cada um contribuísse com um pequeno valor mensal. Refletir: como posso contribuir além do dinheiro? (tempo, dons, presença).", 15),
      step("compromisso", "Compromisso", "Identificar uma forma concreta de contribuir para a Igreja esta semana: dízimo, voluntariado, ou ajuda em alguma atividade da paróquia.", 5),
      step("avisos", "Avisos", "Avisos.", 3),
      step("oracao_final", "Oração Final", "Oração pela missão da Igreja no mundo.", 5),
    ],
  },

  // =====================================================================
  // MÊS DA BÍBLIA 2026 – LIVRO DE DANIEL
  // Tema: "Seu reino jamais será destruído" (Dn 7,14)
  // Proposta da CNBB / Comissão Episcopal para a Animação Bíblico-Catequética
  // =====================================================================
  {
    id: "m58",
    tema: "Mês da Bíblia 2026 – 1º Encontro: Fiéis na Fornalha Ardente",
    categoria: "Mês da Bíblia",
    leituraBiblica: "Dn 3,1-30 – Sadraque, Mesaque e Abede-Nego na fornalha ardente",
    materialApoio: "Subsídio oficial da CNBB – Mês da Bíblia 2026 (Edições CNBB / Paulinas); Texto-base do SAB (Serviço de Animação Bíblica)",
    roteiro: [
      step("acolhida", "Acolhida e Ambientação", "Receber os participantes com música de louvor. Apresentar o cartaz oficial do Mês da Bíblia 2026 e o lema: 'Seu reino jamais será destruído' (Dn 7,14). Introduzir brevemente o Livro de Daniel: um livro escrito para fortalecer o povo em tempos de perseguição e exílio, lembrando que a fidelidade a Deus é mais forte que qualquer poder humano.", 10),
      step("oracao_inicial", "Oração Inicial", "Oração ao Espírito Santo pedindo luz para compreender a Palavra. Acender uma vela no centro do grupo como símbolo da presença de Deus que não se apaga.", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Narrar a história de Dn 3: O rei Nabucodonosor mandou erguer uma estátua de ouro e exigiu que todos a adorassem. Sadraque, Mesaque e Abede-Nego se recusaram. Condenados à fornalha ardente, responderam ao rei: 'Mesmo que Deus não nos salve, não adoraremos os teus deuses.' A fidelidade vai além do resultado! Na fornalha, o rei viu quatro pessoas — a quarta era como um 'filho de Deus' (Dn 3,25). Eles não foram sozinhos. Contextualizar: quais são as 'estátuas de ouro' de hoje? Consumismo, idolatria digital, pressão social, relativismo moral. Como a fé nos sustenta quando somos pressionados a abandonar nossos valores?", 25),
      step("dinamica", "Dinâmica: Minha Fornalha Hoje", "Em pequenos grupos, cada participante responde: 'Quando me sinto pressionado(a) a trair minha fé ou meus valores cristãos?' Cada grupo compartilha uma situação e o grupo todo sugere como Deus pode estar presente nessa 'fornalha' atual.", 15),
      step("compromisso", "Compromisso da Semana", "Identificar um momento desta semana em que será difícil testemunhar a fé (em família, no trabalho, escola) e preparar mentalmente uma resposta corajosa. Escrever o lema 'Seu reino jamais será destruído' em algum lugar visível.", 5),
      step("avisos", "Avisos", "Informes sobre as atividades do Mês da Bíblia na paróquia e comunidade.", 3),
      step("oracao_final", "Oração Final", "Rezar o Salmo 23 juntos: 'Ainda que eu caminhe pelo vale das sombras e da morte, não temerei mal algum, porque estás comigo.' Bênção final.", 5),
    ],
  },
  {
    id: "m59",
    tema: "Mês da Bíblia 2026 – 2º Encontro: O Reino que Não Passa",
    categoria: "Mês da Bíblia",
    leituraBiblica: "Dn 2,31-45; Dn 7,9-14 – A estátua dos reinos e a visão do Filho do Homem",
    materialApoio: "Subsídio oficial da CNBB – Mês da Bíblia 2026 (Edições CNBB / Paulinas); Texto-base do SAB",
    roteiro: [
      step("acolhida", "Acolhida e Retomada", "Retomar o lema do Mês da Bíblia: 'Seu reino jamais será destruído' (Dn 7,14). Perguntar: alguém viveu sua 'fornalha' esta semana (compromisso do 1º encontro)? Partilha breve em duplas.", 10),
      step("oracao_inicial", "Oração Inicial", "Leitura orante de Dn 7,13-14: 'E lhe foi dado o poder, a honra e o reino... Seu poder é eterno, nunca passará, e seu reino jamais será destruído.' Momento de silêncio contemplativo.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Apresentar os dois textos centrais do encontro. Em Dn 2, o rei Nabucodonosor sonha com uma estátua gigante de diferentes metais (ouro, prata, bronze, ferro e barro), que representa os grandes impérios da história — todos poderosos, mas temporários. Uma pedra, sem mão humana, golpeia a estátua e se torna uma grande montanha que enche a terra inteira: é o Reino de Deus. Em Dn 7, Daniel tem a visão do 'Filho do Homem' recebendo um reino eterno de Deus. Para os cristãos, esse Filho do Homem é Jesus Cristo! (Cf. Mc 14,62 e Mt 26,64). Reflexão: os impérios passam — Roma, Babilônia, os grandes poderes. O que realmente dura? Que tipo de 'reino' estamos construindo com nossas escolhas diárias?", 25),
      step("dinamica", "Dinâmica: Construindo o Reino", "Distribuir blocos ou cartões coloridos. Cada participante escreve uma ação concreta que representa 'construir o Reino de Deus' em seu ambiente (família, trabalho, escola, bairro). Montar uma 'torre' com os cartões no centro e ler em voz alta. Reflexão: nossa construção coletiva é parte do Reino eterno.", 15),
      step("compromisso", "Compromisso da Semana", "Escolher uma atitude concreta de construção do Reino: gesto de paz em uma relação difícil, ato de justiça, defesa de um colega injustiçado. Anotar e trazer o resultado no próximo encontro.", 5),
      step("avisos", "Avisos", "Avisos da comunidade e agenda do Mês da Bíblia.", 3),
      step("oracao_final", "Oração Final", "Pai Nosso rezado com ênfase em 'Venha a nós o Teu Reino' — pausar e contemplar o significado desta frase. Bênção final.", 5),
    ],
  },
  {
    id: "m60",
    tema: "Mês da Bíblia 2026 – 3º Encontro: Coragem contra a Injustiça – Susana",
    categoria: "Mês da Bíblia",
    leituraBiblica: "Dn 13,1-64 – A história de Susana: inocência, calúnia e justiça de Deus",
    materialApoio: "Subsídio oficial da CNBB – Mês da Bíblia 2026 (Edições CNBB / Paulinas); Texto-base do SAB (livro deuterocanônico)",
    roteiro: [
      step("acolhida", "Acolhida e Introdução", "Receber os participantes. Notar que hoje abordaremos um capítulo do Livro de Daniel presente na Bíblia Católica (deuterocanônico), mas ausente em outras versões — e explicar brevemente o que são livros deuterocanônicos. Perguntar: vocês já sofreram uma injustiça ou conhecem alguém que sofreu?", 10),
      step("oracao_inicial", "Oração Inicial", "Oração pelos que sofrem injustiça. Aclamar: 'Senhor, tu conheces meu coração. Não me deixa sucumbir à calúnia e ao mal.'", 5, "Oração Simples"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Narrar a história de Susana (Dn 13): Susana era uma mulher justa e bela, casada com um homem rico. Dois anciãos (juízes) passaram a desejá-la e, ao serem rejeitados, a acusaram falsamente de adultério. Condenada à morte, Susana orou: 'Senhor, tu sabes que é falso o que eles testemunharam contra mim.' Deus ouviu e enviou Daniel, jovem ainda, que interrogou os acusadores separadamente e descobriu a contradição em seus testemunhos. Os caluniatores foram condenados. Reflexão: A história denuncia o abuso de poder, a corrupção, o assédio e a calúnia — pecados que ainda existem. Daniel representa a coragem profética de denunciar a injustiça. A oração de Susana é o grito de todo inocente que confia em Deus. Como a fé nos dá coragem para enfrentar situações de injustiça?", 25),
      step("dinamica", "Dinâmica: Voz pelos Inocentes", "Em grupos, refletir sobre: (1) Situações de injustiça presentes na nossa realidade local, nacional ou global. (2) Como posso ser 'Daniel' — alguém que tem coragem de falar a verdade? (3) Elaborar uma oração coletiva pelos que sofrem injustiça hoje. Cada grupo apresenta sua oração.", 15),
      step("compromisso", "Compromisso da Semana", "Agir com coragem diante de uma situação injusta esta semana: defender quem está sendo prejudicado, recusar-se a participar de fofoca ou calúnia, ou orar especificamente por alguém que sofre injustiça.", 5),
      step("avisos", "Avisos", "Avisos da paróquia e atividades do Mês da Bíblia.", 3),
      step("oracao_final", "Oração Final", "Rezar o Salmo 82: 'Fazei justiça ao fraco e ao órfão, amparai o necessitado e o pobre.' Bênção final.", 5),
    ],
  },
  {
    id: "m61",
    tema: "Mês da Bíblia 2026 – 4º Encontro: Esperança que Vence a Morte",
    categoria: "Mês da Bíblia",
    leituraBiblica: "Dn 12,1-4; Dn 7,14 – A ressurreição e a vitória final do Reino de Deus",
    materialApoio: "Subsídio oficial da CNBB – Mês da Bíblia 2026 (Edições CNBB / Paulinas); Texto-base do SAB; Lumen Gentium §48-51",
    roteiro: [
      step("acolhida", "Acolhida e Retomada do Percurso", "Retomar o percurso dos quatro encontros: 1º – Fidelidade na fornalha; 2º – O reino eterno de Deus; 3º – Coragem contra a injustiça. Perguntar: o que ficou marcado neste mês de estudo do Livro de Daniel? Partilha livre.", 10),
      step("oracao_inicial", "Oração Inicial", "Leitura orante de Dn 12,1-3: 'Muitos dos que dormem no pó da terra se hão de despertar... Os sábios resplandecerão como o fulgor do firmamento.' Momento de silêncio e meditação.", 5, "Leitura Orante"),
      step("desenvolvimento", "Desenvolvimento do Tema", "Dn 12 é um dos textos mais importantes do Antigo Testamento: anuncia claramente a ressurreição dos mortos — a primeira vez que esse tema aparece de forma tão explícita no AT. Em tempos de perseguição (dominação selêucida, séc. II a.C.), o livro proclama que nem a morte tem a última palavra. Deus recompensará os justos e os que sofreram por fidelidade à aliança. Para os cristãos, essa esperança se cumpre plenamente em Jesus Cristo ressuscitado (1Cor 15). O lema do Mês da Bíblia — 'Seu reino jamais será destruído' (Dn 7,14) — é a síntese de toda a mensagem: a história humana, com suas crises, perseguições e injustiças, caminha para a vitória definitiva de Deus. Nossa fidelidade hoje não é em vão. Reflexão final: Como vivo a esperança cristã diante das provações da vida? O que significa para mim saber que Deus tem a última palavra?", 25),
      step("dinamica", "Dinâmica: Carta de Esperança", "Cada participante escreve uma 'Carta de Esperança' para si mesmo, como se fosse o Daniel escrevendo para um povo perseguido: quais são as suas 'perseguições' atuais? Qual palavra de Deus você leva do Livro de Daniel? As cartas podem ser lacradas e abertas daqui a um ano, ou compartilhadas voluntariamente com o grupo.", 15),
      step("compromisso", "Compromisso Final do Mês da Bíblia", "Levar o Livro de Daniel para casa e ler ao menos mais um capítulo. Partilhar com alguém de casa o que aprendeu neste Mês da Bíblia. Manter o lema 'Seu reino jamais será destruído' como âncora espiritual nos próximos meses.", 5),
      step("avisos", "Avisos", "Celebração de encerramento do Mês da Bíblia na paróquia. Avisos gerais.", 3),
      step("oracao_final", "Oração Final Solene", "Agradecimento por todo o mês de setembro dedicado à Palavra de Deus. Cantar um hino bíblico (sugestão: 'Tua Palavra é Lâmpada para os meus pés'). Bênção bíblica final: 'Que o Senhor te abençoe e te proteja... e te dê a paz.' (Nm 6,24-26)", 7),
    ],
  },
];
