$path = "c:\Users\Toshiba\Desktop\Projetos no Antigravity\projeto catequese no lovable\src\lib\supabaseStore.ts"
$content = Get-Content $path
$newPrefix = @(
    'import { supabase } from "@/integrations/supabase/client";',
    'import type { Turma, Catequizando, Encontro, Atividade, Paroquia, Comunidade, CatequistaCadastro, RegistroOcorrencia, MuralFoto, CitacaoBiblica, HistoricoSorteioCitacao, BingoModelo } from "./store";',
    '',
    '// ========== TURMAS ==========',
    '',
    'function gerarCodigoTurma(nome: string): string {',
    '  const palavras = nome.trim().split(/\s+/);',
    '  const letra1 = (palavras[0]?.[0] || "A").toUpperCase();',
    '  const letra2 = (palavras[1]?.[0] || palavras[0]?.[1] || "B").toUpperCase();',
    '  // 100000-999999: always exactly 6 digits, no padding needed → total 8 chars',
    '  const digitos = (Math.floor(Math.random() * 900000) + 100000).toString();',
    '  return `${letra1}${letra2}${digitos}`;',
    '}',
    '',
    'export async function fetchTurmas(userId?: string): Promise<Turma[]> {',
    '  let finalUserId = userId;',
    '  ',
    '  if (!finalUserId) {',
    '    const { data: { user } } = await supabase.auth.getUser();',
    '    if (!user) throw new Error("Usuário não autenticado.");',
    '    finalUserId = user.id;',
    '  }',
    '',
    '  // Fetch owned turmas',
    '  const { data: ownedData, error: ownedError } = await (supabase.from as any)("turmas")',
    '    .select("*, turma_catequistas(catequista_id)")',
    '    .eq("user_id", finalUserId)',
    '    .order("criado_em", { ascending: false });',
    '  if (ownedError) throw ownedError;',
    '',
    '  // Fetch turmas where user is a member (shared)',
    '  const { data: memberData, error: memberError } = await (supabase.from as any)("turma_membros")',
    '    .select("turma_id")',
    '    .eq("user_id", finalUserId);',
    '  if (memberError) throw memberError;',
    '',
    '  const sharedIds = (memberData || []).map((m: any) => m.turma_id);',
    '  let sharedTurmas: Turma[] = [];',
    '',
    '  if (sharedIds.length > 0) {',
    '    const { data: sharedData, error: sharedError } = await (supabase.from as any)("turmas")',
    '      .select("*, turma_catequistas(catequista_id)")',
    '      .in("id", sharedIds)',
    '      .order("criado_em", { ascending: false });',
    '    if (sharedError) throw sharedError;',
    '',
    '    sharedTurmas = (sharedData || []).map((t: any) => ({',
    '      id: t.id, nome: t.nome, ano: t.ano, diaCatequese: t.dia_catequese,',
    '      horario: t.horario, local: t.local, etapa: t.etapa, outrosDados: t.outros_dados,',
    '      criadoEm: t.criado_em,',
    '      comunidadeId: t.comunidade_id,',
    '      catequistasIds: (t.turma_catequistas || []).map((tc: any) => tc.catequista_id),',
    '      codigoAcesso: t.codigo_acesso,',
    '      isShared: true,',
    '    }));',
    '  }',
    '',
    '  const ownedTurmas = (ownedData || []).map((t: any) => ({',
    '    id: t.id, nome: t.nome, ano: t.ano, diaCatequese: t.dia_catequese,',
    '    horario: t.horario, local: t.local, etapa: t.etapa, outrosDados: t.outros_dados,',
    '    criadoEm: t.criado_em,',
    '    comunidadeId: t.comunidade_id,',
    '    catequistasIds: (t.turma_catequistas || []).map((tc: any) => tc.catequista_id),',
    '    codigoAcesso: t.codigo_acesso,',
    '    isShared: false,',
    '  }));',
    '',
    '  return [...ownedTurmas, ...sharedTurmas];',
    '}'
)
$rest = $content[65..($content.Length-1)]
$finalContent = $newPrefix + $rest
$finalContent | Set-Content $path
